# Generated by Django 5.2.7 on 2025-11-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('base', models.CharField()),
                ('quote', models.CharField()),
                ('side', models.CharField()),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('is_processed', models.BooleanField()),
                ('opened_at', models.DateTimeField()),
            ],
        ),
    ]
